#!/usr/bin/env bash
# SearxNG + Open WebUI setup
cd "$(dirname "$0")"

SEARXNG_DIR=./searxng
mkdir -p "$SEARXNG_DIR"

# --- settings.yml: only create if absent ---
if [[ ! -f "$SEARXNG_DIR/settings.yml" ]]; then
  {
    echo '# SearxNG settings (generated by setup-searxng.sh)'
    echo 'use_default_settings:'
    echo '  engines:'
    echo '    keep_only:'
    echo '      # DDG excluded: bot-block 202 (CAPTCHA) from this network.'
    echo '      - bing'
    echo '      - brave'
    echo '      - wikipedia'
    echo '      - wikidata'
    echo 'server:'
    echo "  secret_key: \"$(openssl rand -hex 32)\""
    echo '  image_proxy: true'
    echo '  limiter: false'
    echo 'search:'
    echo '  formats:'
    echo '    - html'
    echo '    - json'
  } > "$SEARXNG_DIR/settings.yml"
  echo "created $SEARXNG_DIR/settings.yml"
else
  echo "$SEARXNG_DIR/settings.yml already exists — leaving it untouched"
fi

# --- limiter.toml: only create if absent ---
if [[ ! -f "$SEARXNG_DIR/limiter.toml" ]]; then
  cat > "$SEARXNG_DIR/limiter.toml" <<'EOF'
[real_ip]
# Requests come from the Docker network / local reverse proxy with no
# X-Forwarded-For header; trust private ranges so botdetection doesn't
# error on missing proxy headers.
ipv4 = ['127.0.0.0/8', '10.0.0.0/8', '172.16.0.0/12', '192.168.0.0/16']
ipv6 = ['::1/128', 'fc00::/7']
EOF
  echo "created $SEARXNG_DIR/limiter.toml"
else
  echo "$SEARXNG_DIR/limiter.toml already exists — leaving it untouched"
fi

# Fix ownership if the dir was created by root/another user (container runs as 977).
if [[ "$(id -u)" -eq 0 ]]; then
  chown -R 977:977 "$SEARXNG_DIR"
elif command -v sudo >/dev/null && ! [[ -w "$SEARXNG_DIR" && -O "$SEARXNG_DIR/settings.yml" ]]; then
  sudo chown -R 977:977 "$SEARXNG_DIR"
fi